### PR TITLE
Add sslify wsgi middleware

### PR DESCRIPTION
**Pull request by codingjoe**
sslify

### CODE REVIEW

**Comment by syphar** [comment]
@codingjoe  have to tested this? 

SSL does not reach the dyno, so normally, on heroku, you have to define that the middleware has to use `HTTP_X_FORWARDED_PROTO` to determine if ssl was used.

**Comment by codingjoe** [comment]
@syphar https://github.com/jacobian/wsgi-sslify/issues/2
tho I haven't tested it yet. I'd like to do that in review

**Comment by codingjoe** [comment]
@syphar I just updated the code in case the ever update the default

**Comment by syphar** [comment]
@mostafa-anm @codingjoe what's the status here?

**Comment by codingjoe** [comment]
Merged in 1a3a9058e0d51983eba25d629287936110ef5847

**Pull request closed without merging**
