### PR TITLE
Properly setup multiple buildpacks

### PR DESCRIPTION
**Pull request by durden**
Not sure if the Heroku commands changed, but `heroku buildpacks:set` sets the main buildpack. So, need to use `heroku buildpacks:add --index` to have multiple buildpacks at once.

### CODE REVIEW

**Comment by amureki** [comment]
@durden thank you for this PR!
1. Regarding docs in README.md - this is a good catch, you are right.
2. `post_compile` change is a separate question, and we have next code related to this: https://github.com/Thermondo/sphinx-heroku-buildpack/blob/master/bin/compile#L30

So, I'm not sure this is a necessary change, but if it is, code above should be updated as well. I think, @codingjoe can clarify this moment.

I would say, would be great if you separate or remove `post_compile` thing out of this PR.

P.S. Sorry for no answers for such a long-time. 😅

**Review by codingjoe — APPROVED** [review]

**Comment by codingjoe** [comment]
Thanks @durden 
Sorry that we missed the PR for so long. I wonder why I didn't get any notifications.

**Comment by codingjoe** [comment]
@durden sorry, I didn't see the rename of the `post_compile` file. I had to revert your commit.

**Comment by codingjoe** [comment]
I merged 663af67f98e66e6e0e377d2eb195172215d0b18e again.
Regarding the post_compile. Let's talk about this in the issue. #5

**Pull request merged**
